backend:
  name: git-gateway
  branch: main
media_folder: "public/img/uploads"
public_folder: "img/uploads"
collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - file: "src/_data/site.json"
        label: "Global Settings"
        name: "site"
        fields:
          - {label: "Site Logo", name: "logo", widget: "image", required: true, hint: "Upload the logo that will display in the header and footer."}

  - name: "home"
    label: "Home"
    files:
      - file: "src/_data/home.json"
        label: "Home Content"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }
          - { label: 'Content', name: 'body', widget: 'markdown' }

  - name: "pages"
    label: "Pages"
    folder: "src/_data"
    create: true
    format: "json"
    extension: "json"
    filter: "*.json"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Hero Image", name: "hero_image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "navigation"
    label: "Navigation"
    folder: "src/_data/navigation"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Page",
          name: "page",
          widget: "relation",
          collection: "pages",
          search_fields: ["title"],
          value_field: "permalink",
          display_fields: ["title"]
        }
      - { label: "Order", name: "order", widget: "number", default: 0 }
