backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "public/img/uploads"
public_folder: "img/uploads"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - file: "src/_data/site.json"
        label: "Global Settings"
        name: "site"
        fields:
          - {label: "Site Logo", name: "logo", widget: "image", required: true, hint: "Upload the logo that will display in the header and footer."}
          - {label: "Favicon", name: "favicon", widget: "image", required: true, hint: "Upload your favicon"}

  - name: "home"
    label: "Home"
    files:
      - file: "src/_data/home.json"
        label: "Home Content"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }
          - { label: 'Content', name: 'body', widget: 'markdown' }

  - name: "navigation"
    label: "Navigation Settings"
    files:
      - file: "src/_data/navigation.json"
        label: "Navigation Visibility"
        name: "navsettings"
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            summary: "{{fields.path}} - {{fields.show_in_nav}}"
            fields:
              - { label: "Page Path", name: "path", widget: "string" }
              - { label: "Show in Navigation", name: "show_in_nav", widget: "boolean", default: true }

